# Generated by Django 4.2.6 on 2023-11-23 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informasi', models.CharField(max_length=225)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Portofolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=225)),
                ('keterangan', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
        migrations.AddField(
            model_name='home',
            name='harga',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='home',
            name='nama',
            field=models.CharField(max_length=225),
        ),
        migrations.AddField(
            model_name='blogs',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.home'),
        ),
    ]
